language: php

branches:
  only:
    - master

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm
env:
  - DB_NAME=test
  - DB_USER=travis
  - DB_PASSWORD=''

before_script:
  - if [ ! -d ./tests/data/cache ]; then mkdir -p ./tests/data/cache; fi;
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer install --prefer-dist

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml